### ISSUE TITLE
Front-end issues list

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/matsumoto#43]
- [x] 3) on agent permission page 'Save changes' button is disabled by default but working actually

- [ ] 6) on https://dev.happytravel.com/settings/account and https://dev.happytravel.com/bookings states of sorting and filter is not saved when I leave the page and return back

- [x] 11) I can enter a dot into the children's age fields

- [x] 21) On the last step of Registration, I filled in all the fields on 'Company Information' step, went to the 'Terms & Conditions' page, went back and all the fields are cleared

- [x] 24) during creation a new agent a main page appears after confirmation code confirmation for a 1 sec

**Comment by nikolaeva31** [comment]
https://github.com/happy-travel/agent-app-project/issues/160

**Comment by alexander-plekhanov** [comment]
Number 6 is duplicated in #373. Other is done.

**Comment by sergeyf-QA** [comment]
**Summary:**
- all issues are fixed except 6 - will be fixed in https://github.com/happy-travel/agent-app-project/issues/373

**OK on DEV.**
