### ISSUE TITLE
Mobile version | Issues list

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/matsumoto#55]
Inactual mobile issues list was here.

**Comment by kirillta** [comment]
@sergeyf-QA please update statuses

**Comment by sergeyf-QA** [comment]
@kirillta 
re-tested, all fixed issues I have removed from the description. Now there are only actual bugs.

**Comment by alexander-plekhanov** [comment]
Removed some points that are not actual anymore.

**Comment by alexander-plekhanov** [comment]
Task is done, there are no layout issues in mobile version.

**Comment by sergeyf-QA** [comment]
**Summary:**
- looks fine now

**OK on DEV.**
