### ISSUE TITLE
The situation isn’t handled when a saved card has expired

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/matsumoto#59]
On https://dev.happytravel.com/
In Chrome, Firefox, Safari

**Steps.**
Note: it is likely that the payment with an expired card will be successful - this is a feature of the Payfort system. But in reality, the situation described will happen.
1. Log in with this agent;
https://passbolt.happytravel.com/app/passwords/view/234e4b0d-d430-4b00-8136-4f5935e70834
2. Make any booking and choose Credit card payment option;
3. Choose the first saved card in the list.

**Expectations.**
It would be very convenient for an agent to mark an expired card so that he knows that payment with it isn’t possible.

**Result.**
The situation isn’t handled when a saved card has expired. The agent sees a blank page if he tries to use that card (see pic.)
<img width="1249" alt="Снимок экрана 2021-06-01 в 10 36 16" src="https://user-images.githubusercontent.com/17127277/120339596-eafe9780-c2fd-11eb-959b-c843b298457a.png">

**Comment by alexander-plekhanov** [comment]
Due to payment system migration, saved credit cards functional is deprecated.
