### ISSUE TITLE
Drop-down list doesn't appear if you enter 3 or more characters in the Nationality or Residency field

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/matsumoto#69]
On https://dev.happytravel.com/

Steps:
1. Log in some agent;
2. Type into Nationality or Residency some country name (in example, Russian).

Expected:
The drop-down list is always shown as long as there are corresponding values.
For example, an agent should be able to find the UK by both United... and Britain, and maybe even by Ireland.
https://edo-dev.happytravel.com/en/api/1.0/locations/countries?query=gb
```
[{
    "code": "GB",
    "name": "United Kingdom of Great Britain and Northern Ireland",
    "regionId": 150
}]
```

Result:
Drop-down list doesn't appear if you enter 3 or more characters in the Nationality or Residency field (see drop-down_list_doesnt_appear pic). The drop-down list appears when 2 characters are entered (see drop-down_lis_appears pic.)
![drop-down_lis_appears](https://user-images.githubusercontent.com/17127277/144849705-89b50495-4970-4934-9a2a-669dec92f157.png)
![drop-down_list_doesnt_appear](https://user-images.githubusercontent.com/17127277/144849709-21a9039c-15a1-49ce-87df-077ee73b8019.png)

**Comment by alexander-plekhanov** [comment]
It's an backend issue -- empty array is coming from the api.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now when I enter 3 or more letters of countries name drop down list shows countries inside

**OK on DEV.**
