### ISSUE TITLE
Returning to the filter page does not apply the previously selected filter values

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/matsumoto#78]
On https://manage-dev.happytravel.com/

1. Log in any administrator;
2. Go to All Bookings tab on Bookings Management page https://manage-dev.happytravel.com/bookings/list
3. Select any value in the Supplier field (e.g. RateHawk) and search;
4. Go to any booking’s page in the Bookings list;
5. Click on <Back button;
6. Pay attention to the Bookings list.

**Expectations.**
A list of bookings filtered according to previously selected values.

**Result.**
Returning to the filter page does not apply the previously selected filter values. The list of bookings shows the first 100 bookings, without  the filter values selected.

**Comment by nikolaeva31** [comment]
Fixed
