### ISSUE TITLE
Remove booking status refresh button for bookings with final status

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/matsumoto#82]
Only for the agent app.

It was decided to remove the ability to refresh booking status for bookings in final status:
- Manual Correction Needed;
- Cancelled;
- Rejected;
- Discarded.

If the booking is in any of these statuses, there should be no buttons in the interface to refresh the booking's status.
<img width="720" alt="Снимок экрана 2022-05-11 в 12 13 00" src="https://user-images.githubusercontent.com/17127277/167834999-d1081c47-0a70-4cf8-a48d-d1734a1596de.png">

**Comment by sergeyf-QA** [comment]
**Summary:**
- there is no Refresh button at bookings with Manual Correction Needed, Cancelled, Rejected, Discarded statuses.

**OK on DEV.**
