### ISSUE TITLE
Add a visual indication that the field is required

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/matsumoto#83]
**NOTE: this change is needed in both Matsumoto and UEDA projects**

On https://manage-dev.happytravel.com/ 
1. Log in any administrator;
2. Find any agency and go to edit it;
3. Go to the Details tab (for example https://manage-dev.happytravel.com/agency/770/details);
4. Try to save the data with an empty Locality field.

On https://dev.happytravel.com/
1. Log in any agent;
2. Go to settings -> Agency -> Legal information 
https://dev.happytravel.com/settings/agency
3. Try to save the data with an empty Locality field.

Result.
Many data are required (the server sends message in response), but this is not marked in any way in UI.

To do.
Add a visual indication that the field is required.
In fact, there are more requirements data for an agency than the backend checks. The requirement fields and their validation are very well done in the new agency registration form (see example.jpeg). The agency edit form should behave the same way.

![Image](https://user-images.githubusercontent.com/17127277/170712326-b1fc0217-0383-409e-9267-09c22e3af7ad.jpeg)

**Comment by alexander-plekhanov** [comment]
Fixed for this forms. If needed validation changes in any other forms it should be pointed in special tasks.

**Comment by alexander-plekhanov** [comment]
-
